# Bluffing Detection Using Polynomial Regression

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [2]:
dataset = pd.read_csv('Position_Salaries.csv')
# dataset

In [10]:
x = dataset.iloc[:,1:2].values
y = dataset.iloc[:,2].values

In [11]:
backup = dataset.copy()

In [12]:
# creating Polynomial regression model
poly_reg = PolynomialFeatures(degree=3)
x_poly = poly_reg.fit_transform(x)

lin_reg2 = LinearRegression()
lin_reg2.fit(x_poly,y)

LinearRegression()

In [13]:
poly_pred = lin_reg2.predict(poly_reg.fit_transform([[6.5]]))
poly_pred

array([133259.46969698])

In [14]:
pipe = make_pipeline(lin_reg2)
pipe.fit(x_poly,y)
y_pred = pipe.predict(poly_reg.fit_transform([[6.5]]))

In [15]:
y_pred

array([133259.46969698])

In [16]:
# dummping the model
import pickle

In [17]:
pickle.dump(pipe,open('bluffingDetectionModel.pkl','wb'))

In [27]:
pipe.predict(poly_reg.fit_transform(pd.DataFrame([[4]], columns=['Level'])))

array([88223.77622379])

In [28]:
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000